version: '3.9'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd123
  test-app:
    build: .
    ports: 
      - "8080:80"